### PR TITLE
Add &| and 2>| as pipe operators

### LINKED ISSUE #20: Allow `&|` and `2>|` in pipes
Is it possible to add `&|` and `2>|` as pipe operators? I'm thinking of something like:

```js
pipe: $ => prec.left(seq($._statement, choice('&|', '2>|', '|'), $._statement)),
```

I'm new to tree-sitter and I'm not sure if this may cause any side effects.

For reference: convenience operators in the [fish docs](https://fishshell.com/docs/current/language.html#piping)

### PR DESCRIPTION
**Pull request by piechologist**
Currently, both operators result in errors in the syntax tree.

This PR adds two convenience pipe operators (see the [fish docs](https://fishshell.com/docs/current/language.html#piping)) discussed in #20:

```fish
echo Piping &| cat
echo Piping 2>| cat
```

I changed both `grammar.js` and `grammar.ts` to be able to build the parser locally. The added tests pass using `tree-sitter 0.22.2`. 

I added the operators to `highlights.scm` as well.

Closes #20.

### CODE REVIEW

**Comment by piechologist** [comment]
Oops, looks like an old node version in a GH action? I tested with node v21.7.1 on my local machine.

**Comment by taekwombo** [comment]
Node should be fine, you're free to upgrade - it's not a big deal.
Error in pipeline comes from `@types/node` package. Adding `"moduleResolution": "nodenext"` to `tsconfig.json` fixes errors.

**Comment by taekwombo** [comment]
Looks fine ;) Also please include auto generated files from `src` directory - so that the source is ready to use with your patch applied.

**Comment by piechologist** [comment]
> Adding `"moduleResolution": "nodenext"` to `tsconfig.json` fixes errors.

That did the trick. I've neither upgraded node nor added `ts-ignore`. Didn't want to touch so many things at the same time 😉

I've also incorporated #22 (drop `^`).

Then ran `tree-sitter generate && tree-sitter build` locally with the latest tree-sitter v0.22.2. That's what homebrew gave me. So, those files went into `src`.

Thanks for being patient 😃.

**Review by ram02z — APPROVED** [review]
lgtm. thanks for contributions, @piechologist !

**Pull request merged**
